version: '3'
services:
  db:
    image: postgres:11.0-alpine
    volumes:
      - ./tmp/docker/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/triptych
    ports:
      - "4000:4000"
    depends_on:
      - db
