version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: bin/start
    tty: true
    stdin_open: true
    environment:
      - 'RAILS_YARN_INTEGRITY_CHECK=true'
    volumes:
      - .:/triptych
      - ./docker/data/web/tmp:/triptych/tmp
      - ./docker/data/web/log:/triptych/log
      # - ./docker/data/web/bundle:/usr/local/bundle
      # - ./docker/data/web/node_modules:/triptych/node_modules
  postgres:
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data:rw
  redis:
    volumes:
      - ./docker/data/redis:/data
